# Generated by Django 4.1.1 on 2023-07-15 20:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Devices", "0002_rename_turn_on_devices_state"),
        ("Invitations", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Invitaions",
            new_name="Invitations",
        ),
    ]
