version: '3.9'

services:
  django:
    build: .
    volumes:
      - .:/app
    depends_on:
      - postgres
    
  postgres:
    image: postgres:15.3-alpine3.18
    ports:
      - 5431:5432
    volumes:
      - ../database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  nginx:
    image: nginx:1.25.1
    ports:
      - 8000:80
      - 443:443
    volumes:      
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./staticfiles:/code/static
      - ./config/nginx/ssl:/etc/nginx/certs
    depends_on:
      - django

volumes:
 .:
 database:
 staticfiles: