# Generated by Django 4.1.1 on 2023-06-29 23:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Devices", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="devices",
            old_name="turn_on",
            new_name="state",
        ),
    ]
