# Generated by Django 4.1.1 on 2023-06-09 17:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="devices",
            old_name="typeD",
            new_name="device_type",
        ),
        migrations.RenameField(
            model_name="devices",
            old_name="user",
            new_name="users_id",
        ),
    ]
