# Generated by Django 4.1.1 on 2023-05-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_users_numero"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="imagen_codificada",
            field=models.TextField(default=None),
        ),
        migrations.CreateModel(
            name="Dispositivos",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=30, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=40)),
                ("id_user", models.CharField(editable=False, max_length=30)),
                ("user", models.ManyToManyField(to="app.users")),
            ],
        ),
    ]
