# Generated by Django 4.1.1 on 2023-06-09 18:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_rename_typed_devices_device_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devices",
            name="id",
            field=models.CharField(
                default=uuid.uuid4,
                editable=False,
                max_length=30,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
