# Generated by Django 4.1.1 on 2023-05-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_users_imagen_codificada_dispositivos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
