# Generated by Django 4.1.1 on 2023-06-10 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_alter_devices_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devices",
            name="device_type",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="devices",
            name="id",
            field=models.CharField(
                max_length=30, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="devices",
            name="id_user",
            field=models.CharField(max_length=50),
        ),
    ]
