# Generated by Django 4.1.1 on 2023-05-26 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_users_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="imagen_codificada",
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="numero",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
