# Generated by Django 4.1.1 on 2023-05-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_users_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="users",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
    ]
