# Generated by Django 4.1.1 on 2023-06-12 17:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0006_alter_devices_id_user_alter_devices_users_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="devices",
            old_name="id_user",
            new_name="id_user_main",
        ),
    ]
