# Generated by Django 4.1.1 on 2023-06-21 21:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_rename_id_user_devices_id_user_main"),
    ]

    operations = [
        migrations.AlterField(
            model_name="devices",
            name="id_user_main",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="my_devices",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="devices",
            name="users_id",
            field=models.ManyToManyField(
                related_name="devices", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
