# Generated by Django 4.1.1 on 2023-06-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_users_is_active_users_is_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.CharField(max_length=128, verbose_name="password"),
        ),
    ]
