# Generated by Django 4.1.1 on 2023-06-29 02:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Users", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Devices",
        ),
    ]
